### ISSUE TITLE
ERROR: 下单页面数据解析异常: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by adminpass** [ZhangYikaii/auto-buy-Python-tool#15]
![image](https://user-images.githubusercontent.com/7523220/74587585-8dbed400-502f-11ea-8120-ac2fef924398.png)

抢购无货商品，已抢光时出现

**Comment by zhangyikaii** [comment]
您看看更新的版本噻?

**Comment by adminpass** [comment]
OK，我尽快试下3.0版本，以下是2.0版本抢购出现的error info: 
`2020-02-16 19:59:59,976 INFO: 监控的 0 个商品无货
2020-02-16 20:00:03,526 INFO: 100011385146 编号商品状态: 可配货
2020-02-16 20:00:03,526 INFO: 100011385146 编号商品有货啦! 马上下单
2020-02-16 20:00:03,530 INFO: 第[1/2]次尝试提交订单...
2020-02-16 20:00:05,851 INFO: Traceback (most recent call last):
  File "site-packages\urllib3\connection.py", line 141, in _new_conn
  File "site-packages\urllib3\util\connection.py", line 83, in create_connection
  File "site-packages\urllib3\util\connection.py", line 73, in create_connection
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 346, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
  File "site-packages\urllib3\connection.py", line 284, in connect
  File "site-packages\urllib3\connection.py", line 150, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000002AAA2B85400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 639, in urlopen
  File "site-packages\urllib3\util\retry.py", line 388, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /?cdn=nohost (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002AAA2B85400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "autobuy.py", line 773, in monitorMain
  File "autobuy.py", line 702, in buyGoods
  File "autobuy.py", line 518, in cart_detail
  File "site-packages\requests\sessions.py", line 546, in get
  File "site-packages\requests\sessions.py", line 533, in request
  File "site-packages\requests\sessions.py", line 668, in send
  File "site-packages\requests\sessions.py", line 668, in <listcomp>
  File "site-packages\requests\sessions.py", line 247, in resolve_redirects
  File "site-packages\requests\sessions.py", line 646, in send
  File "site-packages\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /?cdn=nohost (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002AAA2B85400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
`

**Comment by adminpass** [comment]
> 您看看更新的版本噻?
> OK，我尽快试下3.0版本

**以下是2.0版本抢购出现的error info:** 
```
2020-02-16 19:59:59,976 INFO: 监控的 0 个商品无货
2020-02-16 20:00:03,526 INFO: 100011385146 编号商品状态: 可配货
2020-02-16 20:00:03,526 INFO: 100011385146 编号商品有货啦! 马上下单
2020-02-16 20:00:03,530 INFO: 第[1/2]次尝试提交订单...
2020-02-16 20:00:05,851 INFO: Traceback (most recent call last):
  File "site-packages\urllib3\connection.py", line 141, in _new_conn
  File "site-packages\urllib3\util\connection.py", line 83, in create_connection
  File "site-packages\urllib3\util\connection.py", line 73, in create_connection
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 346, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
  File "site-packages\urllib3\connection.py", line 284, in connect
  File "site-packages\urllib3\connection.py", line 150, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000002AAA2B85400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 639, in urlopen
  File "site-packages\urllib3\util\retry.py", line 388, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /?cdn=nohost (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002AAA2B85400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "autobuy.py", line 773, in monitorMain
  File "autobuy.py", line 702, in buyGoods
  File "autobuy.py", line 518, in cart_detail
  File "site-packages\requests\sessions.py", line 546, in get
  File "site-packages\requests\sessions.py", line 533, in request
  File "site-packages\requests\sessions.py", line 668, in send
  File "site-packages\requests\sessions.py", line 668, in <listcomp>
  File "site-packages\requests\sessions.py", line 247, in resolve_redirects
  File "site-packages\requests\sessions.py", line 646, in send
  File "site-packages\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /?cdn=nohost (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002AAA2B85400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
```

**Comment by adminpass** [comment]
> OK，我尽快试下3.0版本

**以下是2.0版本抢购出现的error info:** 
```
2020-02-16 19:59:59,976 INFO: 监控的 0 个商品无货
2020-02-16 20:00:03,526 INFO: 100011385146 编号商品状态: 可配货
2020-02-16 20:00:03,526 INFO: 100011385146 编号商品有货啦! 马上下单
2020-02-16 20:00:03,530 INFO: 第[1/2]次尝试提交订单...
2020-02-16 20:00:05,851 INFO: Traceback (most recent call last):
  File "site-packages\urllib3\connection.py", line 141, in _new_conn
  File "site-packages\urllib3\util\connection.py", line 83, in create_connection
  File "site-packages\urllib3\util\connection.py", line 73, in create_connection
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 346, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
  File "site-packages\urllib3\connection.py", line 284, in connect
  File "site-packages\urllib3\connection.py", line 150, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000002AAA2B85400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 639, in urlopen
  File "site-packages\urllib3\util\retry.py", line 388, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /?cdn=nohost (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002AAA2B85400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "autobuy.py", line 773, in monitorMain
  File "autobuy.py", line 702, in buyGoods
  File "autobuy.py", line 518, in cart_detail
  File "site-packages\requests\sessions.py", line 546, in get
  File "site-packages\requests\sessions.py", line 533, in request
  File "site-packages\requests\sessions.py", line 668, in send
  File "site-packages\requests\sessions.py", line 668, in <listcomp>
  File "site-packages\requests\sessions.py", line 247, in resolve_redirects
  File "site-packages\requests\sessions.py", line 646, in send
  File "site-packages\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /?cdn=nohost (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002AAA2B85400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
```

**Comment by adminpass** [comment]
百度网盘失效(烂移动下不了S3)，麻烦能恢复下，Thanks♪(･ω･)ﾉ @ZhangYikaii

**Comment by ghost** [comment]
> 百度网盘失效(烂移动下不了S3)，麻烦能恢复下，Thanks♪(･ω･)ﾉ @ZhangYikaii

科学上网，就能下GITHUB自己的下载点了。

**Comment by zhangyikaii** [comment]
抱歉昨天有事搞忘了:
链接：https://pan.baidu.com/s/1YfrWjyA0uBNHy4YxcAuI6g 
提取码：m2et
