### ISSUE TITLE
能够监控，但是一直下单失败

### ISSUE THREAD

**Issue by 2505878130** [ZhangYikaii/auto-buy-Python-tool#23]
2020-03-03 01:13:32,126 INFO: 第 7 次查询:
2020-03-03 01:13:32,885 INFO: 监控的 3 个商品所在地区暂无货, 未来可能配货.
2020-03-03 01:13:33,603 INFO: 100011621642 编号商品有货啦! 马上下单.
2020-03-03 01:13:33,607 INFO: 第 1/2 次尝试提交订单...
2020-03-03 01:13:35,800 INFO: Traceback (most recent call last):
  File "site-packages\urllib3\connection.py", line 141, in _new_conn
  File "site-packages\urllib3\util\connection.py", line 83, in create_connection
  File "site-packages\urllib3\util\connection.py", line 73, in create_connection
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 346, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
  File "site-packages\urllib3\connection.py", line 284, in connect
  File "site-packages\urllib3\connection.py", line 150, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001CEC8353160>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 639, in urlopen
  File "site-packages\urllib3\util\retry.py", line 388, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /?cdn=nohost (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001CEC8353160>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "autobuy.py", line 837, in monitorMain
  File "autobuy.py", line 731, in buyGoods
  File "autobuy.py", line 546, in cart_detail
  File "site-packages\requests\sessions.py", line 546, in get
  File "site-packages\requests\sessions.py", line 533, in request
  File "site-packages\requests\sessions.py", line 668, in send
  File "site-packages\requests\sessions.py", line 668, in <listcomp>
  File "site-packages\requests\sessions.py", line 247, in resolve_redirects
  File "site-packages\requests\sessions.py", line 646, in send
  File "site-packages\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /?cdn=nohost (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001CEC8353160>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))

**Comment by zhangyikaii** [comment]
您尝试下关闭代理, 关闭自动配置, 保持网络稳定连接.

**Comment by 2505878130** [comment]
没开代理，网络ok，还是这样
