### ISSUE TITLE
下单页面数据解析异常: list index out of range

### ISSUE THREAD

**Issue by suanve** [ZhangYikaii/auto-buy-Python-tool#30]
![image](https://user-images.githubusercontent.com/35884266/75888972-21cdcf80-5e67-11ea-9954-d11114a664af.png)
2020-03-04 22:25:29,206 INFO: 第[1/5]次尝试提交订单
2020-03-04 22:25:30,291 ERROR: 下单页面数据解析异常: list index out of range
Traceback (most recent call last):
  File "JDAutoBuyTool.py", line 419, in main
    if buyGood(skuId, session, logger, payment_pwd):
  File "JDAutoBuyTool.py", line 363, in buyGood
    if len(risk_control) > 0:
TypeError: object of type 'NoneType' has no len()

求助啊

**Comment by zhangyikaii** [comment]
京东有的时候会拦截, 导致返回的订单页面不正确, 您再多尝试一下?[小纠结]

**Comment by suanve** [comment]
> 京东有的时候会拦截, 导致返回的订单页面不正确, 您再多尝试一下?[小纠结]

我找到问题所在了，是预约抢购的商品，我预约了也不能用脚本抢。🤦‍♂️
